---
- name: Playbook for deploying SS CTF
  hosts: ctfsrv10101.eastus.cloudapp.azure.com
  roles:
    - securityshepherd
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
